// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("Plainion.Core")]
[assembly: AssemblyProduct("Plainion")]
[assembly: AssemblyDescription("Plainion")]
[assembly: AssemblyCopyright("Copyright @ 2020")]
[assembly: AssemblyVersion("4.0.1")]
[assembly: AssemblyFileVersion("4.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.Core";
        internal const System.String AssemblyProduct = "Plainion";
        internal const System.String AssemblyDescription = "Plainion";
        internal const System.String AssemblyCopyright = "Copyright @ 2020";
        internal const System.String AssemblyVersion = "4.0.1";
        internal const System.String AssemblyFileVersion = "4.0.1";
    }
}
