// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Plainion.Core.Tests")]
[assembly: AssemblyProductAttribute("Plainion")]
[assembly: AssemblyDescriptionAttribute("Plainion")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2017")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.Core.Tests";
        internal const System.String AssemblyProduct = "Plainion";
        internal const System.String AssemblyDescription = "Plainion";
        internal const System.String AssemblyCopyright = "Copyright @ 2017";
        internal const System.String AssemblyVersion = "3.0.0";
        internal const System.String AssemblyFileVersion = "3.0.0";
    }
}
